# Generated by Django 2.1.2 on 2018-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_text', models.CharField(max_length=200)),
            ],
        ),
    ]
