# Generated by Django 2.1.2 on 2018-10-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_information',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='blog_content',
            fields=[
                ('blog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='favorite_information',
            fields=[
                ('favorite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('favorite_blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_content')),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='User_ID',
        ),
        migrations.AddField(
            model_name='account_information',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.favorite_information'),
        ),
        migrations.AddField(
            model_name='account_information',
            name='user_blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_content'),
        ),
    ]
