# Generated by Django 2.1.2 on 2018-10-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20181010_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Keyword',
            fields=[
                ('blog_keyword_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='account_information',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='account_information',
            name='user_blog_id',
        ),
        migrations.RemoveField(
            model_name='favorite_information',
            name='favorite_blog_id',
        ),
        migrations.DeleteModel(
            name='account_information',
        ),
        migrations.DeleteModel(
            name='blog_content',
        ),
        migrations.DeleteModel(
            name='favorite_information',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User'),
        ),
        migrations.AddField(
            model_name='blog_keyword',
            name='keyworkd_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Keyword'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User'),
        ),
    ]
